const PRODUCTS = [
  {sku:'LN-10P', name:'Panel Policristalino 10W', price:15.08, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-20P', name:'Panel Policristalino 20W', price:24.03, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-30P', name:'Panel Policristalino 30W', price:29.34, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-50P', name:'Panel Policristalino 50W', price:43.76, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-75P', name:'Panel Policristalino 75W', price:59.34, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-100P', name:'Panel Policristalino 100W', price:68.12, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LN-120M', name:'Panel Monocristalino 120W', price:73.59, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNSB-185M', name:'Panel Monocristalino 185W', price:80.06, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNSB-240M', name:'Panel Monocristalino 240W', price:97.3, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNSE-280P', name:'Panel Policristalino 280W', price:97.79, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNDX-450ND-B', name:'Panel 450W TOPCon Bifacial Full Black', price:135.42, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNCT-585N', name:'Panel 585W TOPCon', price:164.17, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNCT-585ND', name:'Panel 585W TOPCon Bifacial', price:164.17, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNCU-630ND', name:'Panel 630W TOPCon Bifacial', price:172.38, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNVH-630ND', name:'Panel 630W TOPCon Bifacial', price:172.38, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LNET-700ND', name:'Panel 700W TOPCon Bifacial', price:194.09, currency:'USD', category:'paneles', brand:'Siltron', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LR8-66HGD-605M', name:'Panel LONGI 605W', price:194.26, currency:'USD', category:'paneles', brand:'Longi', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LR8-66HGD-610M', name:'Panel LONGI 610W', price:195.92, currency:'USD', category:'paneles', brand:'Longi', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LR8-66HGD-615M', name:'Panel LONGI 615W', price:197.41, currency:'USD', category:'paneles', brand:'Longi', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LR8-66HVD-640M', name:'Panel LONGI 640W Back-Contact', price:227.08, currency:'USD', category:'paneles', brand:'Longi', image:'imagenes/panel_generico1.jpeg'},
  {sku:'LR8-66HVD-650M', name:'Panel LONGI 650W Back-Contact', price:227.08, currency:'USD', category:'paneles', brand:'Longi', image:'imagenes/panel_generico1.jpeg'},
  {sku:'GW1500-XS-30', name:'Inversor On-Grid GoodWe 1500W Monofásico', price:485.65, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW3300-XS-30-AFCI', name:'Inversor On-Grid GoodWe 3300W Monofásico c/AFCI', price:588.41, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW6K-DNS-G40-AFCI', name:'Inversor On-Grid GoodWe 6000W Monofásico c/AFCI', price:866.87, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW2000-MIS', name:'Inversor On-Grid Microinversor GoodWe 2000W', price:371.28, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW6000-SDT-30-AFCI', name:'Inversor On-Grid GoodWe 6kW Trifásico c/AFCI', price:1079.03, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW10K-SDT-30', name:'Inversor On-Grid GoodWe 10kW Trifásico', price:1176.83, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW15K-SDT-30', name:'Inversor On-Grid GoodWe 15kW Trifásico', price:1297.82, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW20K-SDT-30', name:'Inversor On-Grid GoodWe 20kW Trifásico', price:1491.75, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW25K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 25kW Trifásico c/AFCI', price:1765.24, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW30K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 30kW Trifásico c/AFCI', price:1921.04, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW33K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 33kW Trifásico c/AFCI', price:1826.57, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW36K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 36kW Trifásico c/AFCI', price:2164.7, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW40K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 40kW Trifásico c/AFCI', price:2414.98, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'GW50K-SDT-C30-AFCI', name:'Inversor On-Grid GoodWe 50kW Trifásico c/AFCI', price:2572.44, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_compacto.jpeg'},
  {sku:'PIP-1012HSE', name:'Inversor/Cargador Off-Grid MPPSOLAR 12V 1.0/2.0KW PWM 50A', price:293.38, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-2424HSE1', name:'Inversor/Cargador Off-Grid MPPSOLAR 24V 2.4/4.8KW PWM 50A', price:328.19, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-3024HSE', name:'Inversor/Cargador Off-Grid MPPSOLAR 24V 3.0/6.0KW PWM 50A', price:430.95, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-5048HSE', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 5.0/10.0KW PWM 50A', price:500.57, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-1012MSE', name:'Inversor/Cargador Off-Grid MPPSOLAR 12V 1.0/2.0KW MPPT 40A', price:396.14, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-3024MSXE', name:'Inversor/Cargador Off-Grid MPPSOLAR 24V 3.0/6.0KW MPPT 60A', price:487.31, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-3024GEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 24V 3KW MPPT 80A', price:452.5, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-4224GEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 24V 4.2KW MPPT 80A', price:591.73, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-5048GEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 5KW MPPT 80A', price:644.77, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-6248GEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 6.2KW MPPT 80A', price:727.64, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-8KWGEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 8KW MPPT 80A', price:1009.42, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-12KWGEW', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 12KW MPPT 80A', price:1360.81, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-5048MKX', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 5KW MPPT 80A Zero Trf', price:1287.88, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP-11KWMAX', name:'Inversor/Cargador Off-Grid MPPSOLAR 48V 11KW MPPT 80A', price:1306.11, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP4024MT', name:'Inversor/Cargador Off-Grid Inverter/carg 24V 4.0KW Dual Output', price:689.52, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'PIP6048MT', name:'Inversor/Cargador Off-Grid Inverter/carg 48V 6.0KW Dual Output', price:1040.91, currency:'USD', category:'backup', brand:'MPP Solar', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'EM-3224-S1-ECO', name:'Inversor/Cargador Off-Grid EASTMAN 24V 3.2KW MPPT 100A', price:480.68, currency:'USD', category:'backup', brand:'Eastman', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'EM-5548-S1-ECO', name:'Inversor/Cargador Off-Grid EASTMAN 48V 5.5KW MPPT 100A', price:560.24, currency:'USD', category:'backup', brand:'Eastman', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'EM-4024-TW-SI-ULTRA', name:'Inversor/Cargador Off-Grid EASTMAN 24V 4.0KW MPPT 120A', price:689.52, currency:'USD', category:'backup', brand:'Eastman', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'EM-6048-TW-SI-ULTRA', name:'Inversor/Cargador Off-Grid EASTMAN 48V 6.0KW MPPT 120A', price:775.71, currency:'USD', category:'backup', brand:'Eastman', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'EM8000-S1-ULTRA', name:'Inversor/Cargador Off-Grid EASTMAN 48V 8.0KW MPPT 120A', price:1601.15, currency:'USD', category:'backup', brand:'Eastman', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'GW5000-ES-20-HYB', name:'Inversor Híbrido GoodWe Híbrido 5KW Monofásico', price:1778.5, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'GW6000-ES-20-HYB', name:'Inversor Híbrido GoodWe Híbrido 6KW Monofásico', price:1853.09, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'GW12K-ES-C10-AFCI', name:'Inversor Híbrido GoodWe Híbrido 12KW Monofásico', price:2328.79, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'GW10K-ET-L-G10-AFCI', name:'Inversor Híbrido GoodWe Híbrido 10KW Trifásico', price:3550.37, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'GW15K-ET-L-G10-AFCI', name:'Inversor Híbrido GoodWe Híbrido 15KW Trifásico', price:4142.09, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'GW20K-ET-L-G10-AFCI', name:'Inversor Híbrido GoodWe Híbrido 20KW Trifásico', price:4597.91, currency:'USD', category:'backup', brand:'GoodWe', image:'imagenes/inversor_goodwe_grande.jpeg'},
  {sku:'SUN-3K-SG04LP1-EU-SM2', name:'Inversor Híbrido Deye Híbrido 3KW Monofásico', price:1216.61, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-6K-SG03LP1', name:'Inversor Híbrido Deye Híbrido 6KW Monofásico', price:1511.64, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-8K-SG01LP1', name:'Inversor Híbrido Deye Híbrido 8KW Monofásico', price:2123.26, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-8K-SG05LP3-EU-SM2', name:'Inversor Híbrido Deye Híbrido 8KW Trifásico', price:3069.69, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-10K-SG05LP3-EU-SM2', name:'Inversor Híbrido Deye Híbrido 10KW Trifásico', price:3195.66, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-12K-SG05LP3-EU-SM2', name:'Inversor Híbrido Deye Híbrido 12KW Trifásico', price:3290.14, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-15K-SG05LP3-EU-SM2', name:'Inversor Híbrido Deye Híbrido 15KW Trifásico', price:3855.35, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-20K-SG05LP3-EU-SM2', name:'Inversor Híbrido Deye Híbrido 20KW Trifásico', price:5173.06, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-50K-SG01HP3-EU-BM4', name:'Inversor Híbrido Deye Híbrido 50KW Trifásico', price:8758.23, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-80K-SG02HP3-EU-EM6', name:'Inversor Híbrido Deye Híbrido 80KW Trifásico', price:12205.83, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-3.6K-OG01LP1-EU-AM2', name:'Inversor Híbrido Deye Off-Grid 3.6KW Monofásico', price:692.84, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'SUN-6K-OG01LP1-EU-AM2', name:'Inversor Híbrido Deye Off-Grid 6KW Monofásico', price:890.08, currency:'USD', category:'backup', brand:'Deye', image:'imagenes/inversor_deye.jpeg'},
  {sku:'UCG100-12', name:'Batería Ultracell GEL 12V 100Ah', price:266.86, currency:'USD', category:'baterias', brand:'Ultracell', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'UCG200-12', name:'Batería Ultracell GEL 12V 200Ah', price:575.15, currency:'USD', category:'baterias', brand:'Ultracell', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'UCG275-12', name:'Batería Ultracell GEL 12V 275Ah', price:643.11, currency:'USD', category:'baterias', brand:'Ultracell', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'ES-200', name:'Batería Eastman Carbono 12V 200Ah', price:621.56, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'ES-230', name:'Batería Eastman Carbono 12V 230Ah', price:672.95, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'EM12.8-100LPS', name:'Batería Eastman Litio 12V 100Ah', price:474.05, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'EM12.8-150LPS', name:'Batería Eastman Litio 12V 150Ah', price:604.99, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'EM12.8-230LPS', name:'Batería Eastman Litio 12V 230Ah', price:832.07, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'EM25.6-100LPS', name:'Batería Eastman Litio 24V 100Ah', price:788.97, currency:'USD', category:'baterias', brand:'Eastman', image:'imagenes/Bateria.jpeg'},
  {sku:'UP2500', name:'Batería Pylontech UP-2500 24V 2.4kWh', price:1261.36, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'US3000C', name:'Batería Pylontech US-3000C 48V 3.5kWh', price:1460.26, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'UF5000', name:'Batería Pylontech UF-5000 51.2V 5.1kWh', price:1642.58, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'US5000', name:'Batería Pylontech US-5000 48V 4.8kWh', price:1670.76, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'PY-FIDUS', name:'Batería Pylontech FIDUS 51.2V 5.1kWh', price:1768.55, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'PY-FIDUS-PLUS', name:'Batería Pylontech FIDUS PLUS 51.2V 16kWh', price:3989.6, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'PY-BR-US3', name:'Batería Bracket Serie 3000', price:87.85, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'PY-BR-US5', name:'Batería Bracket Serie 5000', price:87.85, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'RT12100G31', name:'Batería Pylontech Litio 12V 100Ah', price:888.42, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'RV12200', name:'Batería Pylontech Litio 12V 200Ah', price:1034.28, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'GW-LX-U5.0-30', name:'Batería GoodWe LV 5.0kWh', price:2192.87, currency:'USD', category:'baterias', brand:'GoodWe', image:'imagenes/Bateria.jpeg'},
  {sku:'GW-HOME-A5.0-30', name:'Batería GoodWe LV 5.0kWh', price:2060.27, currency:'USD', category:'baterias', brand:'GoodWe', image:'imagenes/Bateria.jpeg'},
  {sku:'GW16-BAT-LV-G10', name:'Batería GoodWe LV 16kWh', price:4594.59, currency:'USD', category:'baterias', brand:'GoodWe', image:'imagenes/Bateria.jpeg'},
  {sku:'SE-F5', name:'Batería Deye LV 5.12kWh', price:1420.48, currency:'USD', category:'baterias', brand:'Deye', image:'imagenes/Bateria.jpeg'},
  {sku:'BOS-B-PDU', name:'Batería Deye BOS-B-A3 PDU HV', price:2080.16, currency:'USD', category:'baterias', brand:'Deye', image:'imagenes/Bateria.jpeg'},
  {sku:'BOS-B-PACK-PRO-A3', name:'Batería Deye BOS-B-A3 16kWh HV', price:4024.41, currency:'USD', category:'baterias', brand:'Deye', image:'imagenes/Bateria.jpeg'},
  {sku:'BOS-B-RACK', name:'Batería Deye BOS-B-A3 Rack y Cables', price:1166.88, currency:'USD', category:'baterias', brand:'Deye', image:'imagenes/Bateria.jpeg'},
  {sku:'XLP-10A', name:'Regulador PWM 12/24V 10A', price:15.41, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-20A', name:'Regulador PWM 12/24V 20A', price:19.56, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-30A', name:'Regulador PWM 12/24V 30A', price:29.17, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-40A', name:'Regulador PWM 12/24V 40A', price:39.61, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-50A', name:'Regulador PWM 12/24V 50A', price:31.66, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-60A', name:'Regulador PWM 12/24V 60A', price:60.0, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-50A-48V', name:'Regulador PWM 12/24/48V 50A', price:60.0, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-60A-48V', name:'Regulador PWM 12/24/48V 60A', price:65.14, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-80A-48V', name:'Regulador PWM 12/24/48V 80A', price:91.83, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLP-100A-48V', name:'Regulador PWM 12/24/48V 100A', price:100.44, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLM-2420', name:'Regulador MPPT 12/24V 20A', price:132.6, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLM-2430', name:'Regulador MPPT 12/24V 30A', price:181.5, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLM-2440', name:'Regulador MPPT 12/24V 40A', price:209.51, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'XLM-2460', name:'Regulador MPPT 12/24/36/48V 60A', price:429.29, currency:'USD', category:'backup', brand:'Siltron', image:'imagenes/inversor_mppsolar.jpeg'},
  {sku:'SOP-HE-COP30', name:'Kit Coplanar HOPERGY 4 paneles (30mm)', price:124.64, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-HE-COP35', name:'Kit Coplanar HOPERGY 4 paneles (35mm)', price:124.64, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-NOVA-TILT15', name:'Kit Inclinación 10-15° HOPERGY 4 paneles', price:219.78, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-NOVA-TILT30', name:'Kit Inclinación 15-30° HOPERGY 4 paneles', price:234.37, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-NOVA-TILT60', name:'Kit Inclinación 30-60° HOPERGY 4 paneles', price:260.72, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-HE-GR18', name:'Kit Montaje a suelo 18x2 paneles', price:2123.26, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-PER-COD', name:'Perfil Coda 50x35mm, 6.2mts', price:133.26, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-PER-COD6', name:'Perfil Coda 75x38mm, 6.2mts', price:194.92, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-PER-CP', name:'Perfil C 50x25x3mm, 6mts', price:103.76, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-PER-C', name:'Perfil C 90x30x5mm, 6mts', price:226.25, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-PER-L', name:'Perfil L 50x50x5mm, 6mts', price:114.37, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-OME', name:'Omega con perfil tuerca', price:2.32, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-MOME', name:'Medio Omega con perfil tuerca', price:2.15, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-K-TEJA', name:'Kit Fijación Teja', price:42.76, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-K-CENT', name:'Kit Fijación Central x10u', price:89.01, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-K-CIERRE', name:'Kit Cierre x10u', price:65.14, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'SOP-K-ZAPATA', name:'Kit Zapata Chapa x10u', price:22.71, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'TOR-PLATE', name:'Tornillo soporte a tierra 1600mm c/placa', price:56.02, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'TOR-SPLATE', name:'Tornillo soporte a tierra 1600mm s/placa', price:49.23, currency:'USD', category:'paneles', brand:'Hopergy', image:'imagenes/panel_generico1.jpeg'},
  {sku:'K3SS1.2-56-24-120', name:'Bomba solar sumergible Kunzel 3" 120W 24V Screw', price:202.22, currency:'USD', category:'bombeo', brand:'Kunzel', image:'imagenes/bomba_solar.jpeg'},
  {sku:'K3SP4-50-48-400', name:'Bomba solar sumergible Kunzel 3" 400W 36V Propeller', price:280.12, currency:'USD', category:'bombeo', brand:'Kunzel', image:'imagenes/bomba_solar.jpeg'},
  {sku:'K4SP5.2-67-72-750', name:'Bomba solar sumergible Kunzel 4" 750W 72V Propeller', price:290.06, currency:'USD', category:'bombeo', brand:'Kunzel', image:'imagenes/bomba_solar.jpeg'},
  {sku:'K4SP5.2-146-110-1300', name:'Bomba solar sumergible Kunzel 4" 1300W 110V Propeller', price:334.82, currency:'USD', category:'bombeo', brand:'Kunzel', image:'imagenes/bomba_solar.jpeg'},
  {sku:'K4SP7.5-100-110-1500', name:'Bomba solar sumergible Kunzel 4" 1500W 110V Propeller', price:358.02, currency:'USD', category:'bombeo', brand:'Kunzel', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-2SS1.2-56-24-120', name:'Bomba solar sumergible Hiko 2" 120W 24V Screw', price:268.52, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-2SS1.5-77-24-210', name:'Bomba solar sumergible Hiko 2" 210W 24V Screw', price:271.83, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-2SS1.7-100-48-500', name:'Bomba solar sumergible Hiko 2" 500W 48V Screw', price:341.45, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-3SS1.2-56-24-120', name:'Bomba solar sumergible Hiko 3" 120W 24V Screw', price:309.95, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-3SS1.2-77-36-210', name:'Bomba solar sumergible Hiko 3" 210W 36V Screw', price:316.58, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-3SS4C4-50-48-400', name:'Bomba solar sumergible Hiko 3" 400W 48V Prop Al', price:351.39, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-4SC7-45-72-600', name:'Bomba solar sumergible Hiko 4" 600W 72V Prop ABS', price:323.21, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-4SC7-56-72-750', name:'Bomba solar sumergible Hiko 4" 750W 72V Prop ABS', price:334.82, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HD-4SC7-86-110-1100', name:'Bomba solar sumergible Hiko 4" 1100W 110V Prop ABS', price:358.02, currency:'USD', category:'bombeo', brand:'Hiko Pump', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-0R7G-SS2-PV', name:'Inversor de bombeo INVT Bombeo 0.7kW Monofásico IP20', price:320.23, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-1R5G-SS2-PV', name:'Inversor de bombeo INVT Bombeo 1.5kW Monofásico IP20', price:365.48, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-2R2G-SS2-PV', name:'Inversor de bombeo INVT Bombeo 2.2kW Monofásico IP20', price:407.25, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-2R2G-4-PV', name:'Inversor de bombeo INVT Bombeo 2.2kW Trifásico IP20', price:355.04, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-004G-4-PV', name:'Inversor de bombeo INVT Bombeo 4kW Trifásico IP20', price:476.86, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-5R5G-4-PV', name:'Inversor de bombeo INVT Bombeo 5.5kW Trifásico IP20', price:537.86, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-7R5G-4-PV', name:'Inversor de bombeo INVT Bombeo 7.5kW Trifásico IP20', price:619.57, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-011G-4-PV', name:'Inversor de bombeo INVT Bombeo 11kW Trifásico IP20', price:849.3, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-015G-4-PV', name:'Inversor de bombeo INVT Bombeo 15kW Trifásico IP20', price:1019.86, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-018G-4-PV', name:'Inversor de bombeo INVT Bombeo 18kW Trifásico IP20', price:1148.65, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-022G-4-PV', name:'Inversor de bombeo INVT Bombeo 22kW Trifásico IP20', price:1374.9, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-030G-4-PV', name:'Inversor de bombeo INVT Bombeo 30kW Trifásico IP20', price:1635.95, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-037G-4-PV', name:'Inversor de bombeo INVT Bombeo 37kW Trifásico IP20', price:2036.24, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-045G-4-PV', name:'Inversor de bombeo INVT Bombeo 45kW Trifásico IP20', price:2596.64, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-055G-4-PV', name:'Inversor de bombeo INVT Bombeo 55kW Trifásico IP20', price:2706.37, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-075G-4-PV', name:'Inversor de bombeo INVT Bombeo 75kW Trifásico IP20', price:3278.87, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-090G-4-PV', name:'Inversor de bombeo INVT Bombeo 90kW Trifásico IP20', price:3853.19, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'GD100-110G-4-PV', name:'Inversor de bombeo INVT Bombeo 110kW Trifásico IP20', price:4277.84, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-0K7-TN-AC', name:'Inversor de bombeo INVT Bombeo 0.7kW Monofásico IP65', price:734.46, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-1KS-TN-AC', name:'Inversor de bombeo INVT Bombeo 1.5kW Monofásico IP65', price:831.9, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-2K2-TN-AC', name:'Inversor de bombeo INVT Bombeo 2.2kW Monofásico IP65', price:974.61, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-004-TN-AC', name:'Inversor de bombeo INVT Bombeo 4kW Monofásico IP65', price:1444.51, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-2K2-TRAC', name:'Inversor de bombeo INVT Bombeo 2.2kW Trifásico IP65', price:939.8, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-004-TRAC', name:'Inversor de bombeo INVT Bombeo 4kW Trifásico IP65', price:1221.75, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BPD-5KS-TRAC', name:'Inversor de bombeo INVT Bombeo 5.5kW Trifásico IP65', price:1270.47, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SP100-0R7-2-T-6-S', name:'Inversor de bombeo INVT Bombeo 0.7kW Monofásico IP66', price:672.78, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SP100-1R5-2-T-6-S', name:'Inversor de bombeo INVT Bombeo 1.5kW Monofásico IP66', price:795.77, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SP100-2R2-2-T-6-S', name:'Inversor de bombeo INVT Bombeo 2.2kW Monofásico IP66', price:881.46, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SP100-2R2-4-T-6-S', name:'Inversor de bombeo INVT Bombeo 2.2kW Trifásico IP66', price:699.63, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SP100-004-4-T-6-S', name:'Inversor de bombeo INVT Bombeo 4kW Trifásico IP66', price:807.53, currency:'USD', category:'bombeo', brand:'INVT', image:'imagenes/bomba_solar.jpeg'},
  {sku:'JKM460N-48HL4M-DV', name:'Panel solar Jinko 460W Monofacial', price:181.17, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM445N-48HL4M-BDV', name:'Panel solar Jinko 445W Bifacial', price:180.92, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM550M72HL4V30', name:'Panel solar Jinko 550W Mono Perc', price:214.62, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM590N-72HL4-V', name:'Panel solar Jinko 590W Monofacial', price:214.17, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM610N-66HL4M-(V)', name:'Panel solar Jinko 610W Bifacial', price:240.25, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM620N-66HL4M-(V)', name:'Panel solar Jinko 620W Bifacial', price:246.44, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM630N-66HL4M-BDV', name:'Panel solar Jinko 630W Bifacial', price:227.55, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM650N-66QL6-BDV', name:'Panel solar Jinko 650W Bifacial', price:278.42, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JKM725N-66HL5-BDV', name:'Panel solar Jinko 725W Bifacial', price:288.19, currency:'USD', category:'paneles', brand:'Jinko', image:'imagenes/panel_generico2.jpeg'},
  {sku:'TSM-510DE18M (II)', name:'Panel solar Trina 510W Monofacial', price:185.13, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'DE19R565W-30MM', name:'Panel solar Trina 565W Monofacial', price:205.1, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'DE19R570W-30mm', name:'Panel solar Trina 570W Monofacial', price:206.91, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'DE19R575W-30mm', name:'Panel solar Trina 575W Monofacial', price:208.73, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'TSM-620NEG19RC.20', name:'Panel solar Trina 620W Bifacial', price:241.94, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'TSM-625NEG19RC.20', name:'Panel solar Trina 625W Bifacial', price:241.63, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'TSM-710NEG21C.20', name:'Panel solar Trina 710W Bifacial', price:257.73, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'TSM-715NEG21C.20', name:'Panel solar Trina 715W Bifacial', price:259.55, currency:'USD', category:'paneles', brand:'Trina', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JAM66D45-615W/LB', name:'Panel solar JA Solar 615W Bifacial', price:222.13, currency:'USD', category:'paneles', brand:'JA', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JAM66D45-620/LB', name:'Panel solar JA Solar 620W Bifacial', price:246.44, currency:'USD', category:'paneles', brand:'JA', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JAM66D45-625W/LB', name:'Panel solar JA Solar 625W Bifacial', price:245.03, currency:'USD', category:'paneles', brand:'JA', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JAM66D45-630/LB', name:'Panel solar JA Solar 630W Bifacial', price:227.55, currency:'USD', category:'paneles', brand:'JA', image:'imagenes/panel_generico2.jpeg'},
  {sku:'JAM66D46-735/LB', name:'Panel solar JA Solar 735W Bifacial', price:284.15, currency:'USD', category:'paneles', brand:'JA', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M28-100W', name:'Panel solar Amerisolar 100W', price:62.07, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-8M13-200W', name:'Panel solar Amerisolar 200W', price:130.68, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-6P30-285W', name:'Panel solar Amerisolar 285W Policristalino', price:130.68, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-6P-340W', name:'Panel solar Amerisolar 340W Policristalino', price:175.87, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M108-HC-430W', name:'Panel solar Amerisolar 430W', price:156.09, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M132FL-460W', name:'Panel solar Amerisolar 460W Flexible', price:377.37, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M120N-HC-470W', name:'Panel solar Amerisolar 470W', price:185.97, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M144-HC-555W30', name:'Panel solar Amerisolar 555W', price:192.41, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M144N-HC-580W', name:'Panel solar Amerisolar 580W', price:201.07, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'ALL-BLACK-555W', name:'Panel solar Amerisolar 555W All Black', price:214.75, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'ALL BLACK 580W', name:'Panel solar Amerisolar 580W All Black', price:229.49, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'AS-7M144N-BHC-600W', name:'Panel solar Amerisolar 600W Bifacial', price:208.0, currency:'USD', category:'paneles', brand:'Amerisolar', image:'imagenes/panel_generico2.jpeg'},
  {sku:'UP5000-MR', name:'Batería Pylontech Pylontech 48V 4800Wh (Multiradio)', price:2395.8, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'UF5000-MR', name:'Batería Pylontech Pylontech 51.2V 5120Wh (Multiradio)', price:2085.44, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'BRACKET-UF5000-MR', name:'Batería Pylontech Bracket US5000/UP5000/UF5000 (Multiradio)', price:119.79, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'FB-L-5.12-MR', name:'Batería Pylontech Pylontech FIDUS 51.2V 5120Wh (Multiradio)', price:2203.41, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'BRACKETFIDUS5.12-MR', name:'Batería Pylontech Bracket Fidus (Multiradio)', price:21.78, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'FIDUSWIFISTICK-MR', name:'Batería Pylontech Dongle WiFi Fidus (Multiradio)', price:67.16, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'FB-L-16-PRO-MR', name:'Batería Pylontech Pylontech FIDUS 51.2V 16076Wh (Multiradio)', price:5414.15, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'WHEEL-FB-L-16-PRO-MR', name:'Batería Pylontech Kit ruedas FB-L-16-PRO (Multiradio)', price:23.6, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'RACK-FB-L-16-PRO-MR', name:'Batería Pylontech Rack pared FB-L-16-PRO (Multiradio)', price:32.67, currency:'USD', category:'baterias', brand:'Pylontech', image:'imagenes/UP5000_ENEICA.jpg'},
  {sku:'WSOLARHEAT150L', name:'Termotanque Solar 150L c/entrada superior', price:781804.34, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHT150LSA', name:'Termotanque Solar 150L s/entrada superior', price:781804.34, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHEAT200L', name:'Termotanque Solar 200L c/entrada superior', price:831548.2, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHT200LSA', name:'Termotanque Solar 200L s/entrada superior', price:831548.2, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTE+TP200', name:'Termotanque Solar 200L c/tanque prellenado', price:891388.84, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHEAT250L', name:'Termotanque Solar 250L c/entrada superior', price:1070737.76, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHT250LSA', name:'Termotanque Solar 250L s/entrada superior', price:1070737.76, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTE+TP250', name:'Termotanque Solar 250L c/tanque prellenado', price:1130583.41, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHEAT280L', name:'Termotanque Solar 280L', price:1130485.21, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHEAT300L', name:'Termotanque Solar 300L c/entrada superior', price:1285531.96, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHT300LSA', name:'Termotanque Solar 300L s/entrada superior', price:1285531.96, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTE+TP300', name:'Termotanque Solar 300L c/tanque prellenado', price:1345378.42, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARHEAT360L', name:'Termotanque Solar 360L c/entrada superior', price:1636980.21, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTE+TP360', name:'Termotanque Solar 360L c/tanque prellenado', price:1696828.86, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE100L', name:'Termotanque Heat Pipe 100L', price:1187736.17, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE100A', name:'Termotanque Heat Pipe 100L Inox', price:1384149.43, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE200L', name:'Termotanque Heat Pipe 200L', price:1893527.32, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE200A', name:'Termotanque Heat Pipe 200L Inox', price:2206655.66, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE280L', name:'Termotanque Heat Pipe 280L', price:2583582.32, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE300L', name:'Termotanque Heat Pipe 300L', price:2767871.71, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARCOLECH25', name:'Colector Solar 25 Tubos', price:1753242.18, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARCOLEHP15', name:'Colector Heat Pipe 15 Tubos (solo colector)', price:841556.25, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARCOLECH15', name:'Colector Heat Pipe 15 Tubos', price:1051945.33, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARCOLEHP20', name:'Colector Heat Pipe 20 Tubos (solo colector)', price:1412387.99, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME130', name:'Estructura Termo Solar 130L', price:302994.69, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME150', name:'Estructura + Cuna Termo 150L', price:150996.89, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME200', name:'Estructura + Cuna Termo 200L', price:201329.66, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME250', name:'Estructura + Cuna Termo 250L', price:251662.42, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME280', name:'Estructura Termo Solar 280L', price:605989.15, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME300', name:'Estructura + Cuna Termo 300L', price:301995.18, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAME360', name:'Estructura + Cuna Termo 360L', price:362394.88, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMEC15', name:'Estructura Colector Heat Pipe 15T', price:40057.26, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMEC20', name:'Estructura Colector Heat Pipe 20T', price:40057.26, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMEC25', name:'Estructura Colector Heat Pipe 25T', price:40057.26, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMEC30', name:'Estructura Colector Heat Pipe 30T', price:432847.68, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMH200', name:'Estructura Termo Heat Pipe 200L', price:432847.68, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMH300', name:'Estructura Termo Heat Pipe 300L', price:649244.2, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAMH360', name:'Estructura Termo Heat Pipe 360L', price:779006.03, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAAC150', name:'Estructura Termo 150L Ainox', price:371616.67, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAAC200', name:'Estructura Termo 200L Ainox', price:519482.4, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAAC250', name:'Estructura Termo 250L Ainox', price:649352.86, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARFRAAC300', name:'Estructura Termo 300L Ainox', price:779006.03, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK100L', name:'Tanque Termo Solar 100L', price:339604.1, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK130L', name:'Tanque Termo Solar 130L', price:463186.52, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK150L', name:'Tanque Termo Solar 150L', price:534446.25, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK200L', name:'Tanque Termo Solar 200L', price:624390.93, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK250L', name:'Tanque Termo Solar 250L', price:780487.51, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK280L', name:'Tanque Termo Solar 280L', price:874146.12, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK300L', name:'Tanque Termo Solar 300L', price:936586.08, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANK360L', name:'Tanque Termo Solar 360L', price:1123898.04, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANIT200', name:'Tanque Tank in Tank 200L', price:1097963.97, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANIT300', name:'Tanque Tank in Tank 300L', price:1813165.97, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTANQ200L', name:'Tanque Termo Solar 200L (línea 2)', price:624390.93, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WTANQHPIPE100', name:'Tanque Heat Pipe 100L', price:947879.64, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WTANQHPIPEI100', name:'Tanque Heat Pipe 100L Inox', price:1104628.38, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WTANQHPIPEI200', name:'Tanque Heat Pipe 200L Inox', price:1634525.99, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE300', name:'Tanque Heat Pipe 300L', price:1980538.62, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WTANQHPIPEI300', name:'Tanque Heat Pipe 300L Inox', price:2411552.67, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARPIPE360', name:'Tanque Heat Pipe 360L', price:2376649.35, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WTANQHPIPEI360', name:'Tanque Heat Pipe 360L Inox', price:2893863.3, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WMAGNESBARGB', name:'Barra Magnesio 58mm', price:8919.8, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WMAGNESBARHEAT', name:'Barra Magnesio Heat Pipe', price:30984.44, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WMAGNESBARHPLG', name:'Barra Magnesio HP Larga', price:30984.44, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WMAGNESBARHPCR', name:'Barra Magnesio HP Corta', price:30984.44, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACESSSR81', name:'Controlador SR81', price:273163.73, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACESSSR81CONT', name:'Controlador SR81 s/Display', price:251836.34, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCES220VCONT', name:'Controlador SR500 220V', price:145189.87, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCES12VCONT', name:'Controlador SR500 12V', price:145189.87, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCESTK8A3KW', name:'Controlador TK8-A 220V 3kW', price:94186.25, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTRESIS2K', name:'Resistencia 2kW s/Termostato', price:24178.65, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTRIP1REF', name:'Soporte Trípode 1 Reflector', price:35258.75, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTRIP2REF', name:'Soporte Trípode 2 Reflectores', price:39327.24, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTAPRE200', name:'Tanque Prellenado 3/4', price:59841.53, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTAPRESAI', name:'Tanque Prellenado 3/4 Inox', price:68817.74, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTAPRE1/2', name:'Tanque Prellenado 5L 1/2', price:59841.53, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WSOLARTAPRESLT', name:'Tanque Prellenado SLTR 1/2', price:59841.53, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCESOPTANK', name:'Apoya Tanque Prellenado', price:5292.13, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCESCUNATANK', name:'Cuna Metálica 100L', price:117184.65, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCESCUNATANT', name:'Cuna Metálica 150L+', price:117184.65, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'WACCESCUNATAIN', name:'Cuna Metálica Inox', price:117184.65, currency:'ARS', category:'bombeo', brand:'Hissuma', image:'imagenes/fondiododo.png'},
  {sku:'6083536', name:'Bomba sumergible Wilo Actun FIRST SPU4.05-06-B-50-0,55', price:438.24, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.01-10B', name:'Bomba sumergible Wilo SPU 4.01-10B', price:104.9, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.01-13B', name:'Bomba sumergible Wilo SPU 4.01-13B', price:121.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.01-19B', name:'Bomba sumergible Wilo SPU 4.01-19B', price:147.73, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.01-26B', name:'Bomba sumergible Wilo SPU 4.01-26B', price:202.97, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.01-38B', name:'Bomba sumergible Wilo SPU 4.01-38B', price:291.11, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.06-07B', name:'Bomba sumergible Wilo SPU 4.06-07B', price:110.49, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.06-10B', name:'Bomba sumergible Wilo SPU 4.06-10B', price:157.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.06-20B', name:'Bomba sumergible Wilo SPU 4.06-20B', price:251.38, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.06-36B', name:'Bomba sumergible Wilo SPU 4.06-36B', price:451.25, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.08-04B', name:'Bomba sumergible Wilo SPU 4.08-04B', price:95.59, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.08-06B', name:'Bomba sumergible Wilo SPU 4.08-06B', price:121.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.08-13B', name:'Bomba sumergible Wilo SPU 4.08-13B', price:186.21, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.08-23B', name:'Bomba sumergible Wilo SPU 4.08-23B', price:297.94, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.12-07B', name:'Bomba sumergible Wilo SPU 4.12-07B', price:152.07, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.12-10B', name:'Bomba sumergible Wilo SPU 4.12-10B', price:186.21, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.12-19B', name:'Bomba sumergible Wilo SPU 4.12-19B', price:242.69, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.12-26B', name:'Bomba sumergible Wilo SPU 4.12-26B', price:307.25, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.16-07B', name:'Bomba sumergible Wilo SPU 4.16-07B', price:186.21, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.16-14B', name:'Bomba sumergible Wilo SPU 4.16-14B', price:248.28, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.16-19B', name:'Bomba sumergible Wilo SPU 4.16-19B', price:310.35, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SPU4.16-27B', name:'Bomba sumergible Wilo SPU 4.16-27B', price:372.42, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PB 088', name:'Bomba de superficie/presurizadora Wilo PB 088 EA', price:108.0, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PB 201 EA', name:'Bomba de superficie/presurizadora Wilo PB 201 EA', price:193.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PW 175 EA', name:'Bomba de superficie/presurizadora Wilo PW 175 EA', price:193.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiPeri 1-4 PAC', name:'Bomba de superficie/presurizadora Wilo HiPeri 1-4 PAC', price:258.83, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PAR 30 PAC', name:'Bomba de superficie/presurizadora Wilo PAR 30 PAC', price:381.11, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiMulti 3-23 CP', name:'Bomba de superficie/presurizadora Wilo HiMulti 3-23 CP', price:842.29, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiMulti 3-24 CP', name:'Bomba de superficie/presurizadora Wilo HiMulti 3-24 CP', price:858.43, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiMulti 3-43 CP', name:'Bomba de superficie/presurizadora Wilo HiMulti 3-43 CP', price:840.43, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiMulti 3-44 CP', name:'Bomba de superficie/presurizadora Wilo HiMulti 3-44 CP', price:851.6, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PE-350EA', name:'Bomba de superficie/presurizadora Wilo PE-350EA', price:427.66, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PBI-L304EA', name:'Bomba de superficie/presurizadora Wilo PBI-L304EA', price:1029.12, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'PBI-L603EA', name:'Bomba de superficie/presurizadora Wilo PBI-L603EA', price:1158.85, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'MHKE 205A', name:'Bomba de superficie/presurizadora Wilo MHKE 205A', price:1284.23, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'MHKE 803A', name:'Bomba de superficie/presurizadora Wilo MHKE 803A', price:1310.92, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'HiMulti 5-45 iPQ', name:'Bomba de superficie/presurizadora Wilo HiMulti 5-45 iPQ', price:1128.43, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'T-KIT Universal', name:'Accesorio Wilo Válvula 3 vías', price:62.07, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'T-KIT PLUS 1"', name:'Accesorio Wilo Válvula 5 vías 1"', price:32.9, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'T-KIT PLUS 1 1/4"', name:'Accesorio Wilo Válvula 5 vías 1 1/4"', price:55.86, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'T-KIT PLUS 1 1/2"', name:'Accesorio Wilo Válvula 5 vías 1 1/2"', price:59.59, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BE-WP-1x16A', name:'Accesorio Wilo Tablero 1 bomba 16A', price:393.52, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'BE-WP-1x25A', name:'Accesorio Wilo Tablero 1 bomba 25A', price:506.49, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'MS-L-1x4KW-DOL', name:'Accesorio Wilo Tablero 1 bomba 4kW', price:498.42, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'MS-L-2x4KW-DOL', name:'Accesorio Wilo Tablero 2 bombas 4kW', price:690.22, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'EC-L 2x12A MT 34', name:'Accesorio Wilo Tablero Easy Lift 2x12A', price:1087.47, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'EC-B-2x12A-MT34', name:'Accesorio Wilo Tablero Easy Boost 2x12A', price:1215.33, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SpeedBox 1112 MM', name:'Accesorio Wilo SpeedBox 1112 MM', price:544.98, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SpeedBoard 1010 MT', name:'Accesorio Wilo SpeedBoard 1010 MT', price:601.46, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SpeedBox 1325 TT', name:'Accesorio Wilo SpeedBox 1325 TT', price:1960.17, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'SpeedBox Duo', name:'Accesorio Wilo SpeedBox Duo', price:759.11, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'Switchmatic 2', name:'Accesorio Wilo Switchmatic 2', price:80.07, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'Switchmatic 2 T', name:'Accesorio Wilo Switchmatic 2 T', price:178.14, currency:'USD', category:'bombeo', brand:'Wilo', image:'imagenes/bomba_solar.jpeg'},
  {sku:'MP 6 2,8', name:'Batería Maxton GEL/AGM Batería 6V 2.8Ah', price:10.13, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 6 - 4', name:'Batería Maxton GEL/AGM Batería 6V 4Ah', price:10.73, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 6 - 10', name:'Batería Maxton GEL/AGM Batería 6V 10Ah', price:16.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 4,5', name:'Batería Maxton GEL/AGM Batería 12V 4.5Ah', price:15.29, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 6', name:'Batería Maxton GEL/AGM Batería 12V 6Ah', price:17.25, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 7D', name:'Batería Maxton GEL/AGM Batería 12V 7Ah', price:17.25, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 7', name:'Batería Maxton GEL/AGM Batería 12V 7Ah', price:19.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 9', name:'Batería Maxton GEL/AGM Batería 12V 9Ah', price:25.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 12', name:'Batería Maxton GEL/AGM Batería 12V 12Ah', price:34.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 17', name:'Batería Maxton GEL/AGM Batería 12V 17Ah', price:46.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 18', name:'Batería Maxton GEL/AGM Batería 12V 18Ah', price:49.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 20', name:'Batería Maxton GEL/AGM Batería 12V 20Ah', price:73.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 26', name:'Batería Maxton GEL/AGM Batería 12V 26Ah', price:78.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12-30D', name:'Batería Maxton GEL/AGM Batería 12V 30Ah', price:105.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 33', name:'Batería Maxton GEL/AGM Batería 12V 33Ah', price:102.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 45', name:'Batería Maxton GEL/AGM Batería 12V 45Ah', price:135.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 55', name:'Batería Maxton GEL/AGM Batería 12V 55Ah', price:165.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 12 - 65', name:'Batería Maxton GEL/AGM Batería 12V 65Ah', price:198.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 75', name:'Batería Maxton GEL/AGM Batería 12V 75Ah', price:225.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 100', name:'Batería Maxton GEL/AGM Batería 12V 100Ah', price:292.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 150', name:'Batería Maxton GEL/AGM Batería 12V 150Ah', price:570.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 225', name:'Batería Maxton GEL/AGM Batería 12V 225Ah', price:615.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 250', name:'Batería Maxton GEL/AGM Batería 12V 250Ah', price:645.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 12 - 275', name:'Batería Maxton GEL/AGM Batería 12V 275Ah', price:645.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPEV 8 - 170', name:'Batería Maxton GEL/AGM Batería 8V 170Ah', price:352.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPE 6 - 225', name:'Batería Maxton GEL/AGM Batería 6V 225Ah', price:420.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MPEV 6 - 225', name:'Batería Maxton GEL/AGM Batería 6V 225Ah', price:375.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 100E', name:'Batería Maxton GEL/AGM Batería 12V 100Ah', price:237.0, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
  {sku:'MP 200E', name:'Batería Maxton GEL/AGM Batería 12V 200Ah', price:487.5, currency:'USD', category:'baterias', brand:'Maxton', image:'imagenes/bateria_ultra.jpeg'},
];